# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image:
  name: moreaghost/morea-ghost:2017.11.30-4
  username: $DOCKER_HUB_LOGIN
  password: $DOCKER_HUB_PASSWORD
  email: ghost-devops@morea.fr

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - git --version
          - git status
          - git submodule update --init
          - tox --version
          - cp config.yml.sample config.yml
          - tox
